prefix:
  pathopipe
units:
  units.tsv
genera:
  targets.tsv
db:
  /maps/projects/lundbeck/data/dbs/krakenuniq/hum_microbe
kmers:
  150
MQ:
  20
tmp_dir:
  /dev/shm/pathopipe
bt2_param:
  "-D 20 -R 3 -N 1 -L 20 -i S,1,0.50"
targets_priority:
  targets_priority.tsv
metaDMG-cpp:
  /home/dsw670/progs/metaDMG-cpp/metaDMG-cpp
