prefix:
  pathopipe
units:
  units.tsv
genera:
  targets.tsv
db:
  /maps/projects/lundbeck/data/dbs/krakenuniq/hum_microbe
krakenuniq_memory:
  64G
kmers:
  50
MQ:
  20
tmp_dir:
  /dev/shm/pathopipe
mm2_param:
  "-x sr"
targets_priority:
  targets_priority.tsv
metaDMG-cpp:
  /home/dsw670/progs/metaDMG-cpp/metaDMG-cpp
